version: '3.8'
services:
  app:
    build: .
    container_name: banner_service_app
    restart: always
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8888"
    env_file:
      - .env
    ports:
      - "8888:8888"

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ../redis_data:/var/lib/redis/data/


  celery:
    container_name: celery
    build: .
    command: celery -A config worker -l INFO
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      # - CELERY_BROKER_URL=redis://redis:6900/0


  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A config beat -l INFO
    depends_on:
      - redis
