# Generated by Django 5.0.4 on 2024-04-09 09:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField(unique=True)),
                ('tag_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(unique=True), size=None)),
                ('title', models.CharField(blank=True, default='title', max_length=25, null=True)),
                ('description', models.CharField(blank=True, default='description', max_length=250, null=True)),
                ('url', models.URLField(blank=True, default='https://www.avito.ru/я-вас-люблю', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('feature_id', 'tag_ids')},
            },
        ),
    ]
