# Generated by Django 5.0.4 on 2024-04-07 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.feature')),
                ('tag_ids', models.ManyToManyField(related_name='tags', to='main.tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.UniqueConstraint(fields=('feature_id',), name='unique_banner_tag'),
        ),
    ]
