# Generated by Django 5.0.4 on 2024-04-10 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='banner',
            unique_together=set(),
        ),
    ]
