# Generated by Django 5.0.4 on 2024-04-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='feature_id',
            field=models.IntegerField(),
        ),
    ]
