# Generated by Django 5.0.4 on 2024-04-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bannertag_remove_banner_unique_banner_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='content',
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.CharField(blank=True, default='description', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, default='https://www.avito.ru/', null=True),
        ),
    ]
