# Generated by Django 5.0.4 on 2024-04-12 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bannerversion_banner_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerversion',
            name='banner_id',
        ),
        migrations.AddField(
            model_name='bannerversion',
            name='banner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.banner'),
            preserve_default=False,
        ),
    ]
