# Generated by Django 5.0.4 on 2024-04-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_banner_content_banner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, default='https://www.avito.ru/я-вас-люблю', null=True),
        ),
    ]
