# Generated by Django 5.0.4 on 2024-04-07 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='bannertag',
            unique_together={('banner', 'tag')},
        ),
    ]
